#!/usr/bin/python3
import subprocess

proc = subprocess.Popen(f'sudo -s cp tlauncher /bin',shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate(input=b'Sudo password: \n')
